"""empty message

Revision ID: 35cd7d4a111a
Revises: 8c7e4aad722b
Create Date: 2026-07-12 10:55:55.828695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cd7d4a111a'
down_revision = '8c7e4aad722b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_of_residence', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('state_of_residence')

    # ### end Alembic commands ###
