"""empty message

Revision ID: 69c8bb96b8bf
Revises: 89d1221aa8c4
Create Date: 2026-07-13 20:48:24.373155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69c8bb96b8bf'
down_revision = '89d1221aa8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
