"""empty message

Revision ID: 89d1221aa8c4
Revises: 35cd7d4a111a
Create Date: 2026-07-13 15:30:37.820141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89d1221aa8c4'
down_revision = '35cd7d4a111a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=10), nullable=True))
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
